[project]
name = "dual_ifm"
version = "0.1.0"
description = """Repository for the paper <<Towards Interpretable Foundation Models for Retinal Images>>"""
license = "MIT"
requires-python = ">=3.12"
dependencies = [
    "annoy>=1.17.3",
    "cairosvg>=2.9.0",
    "glasbey>=0.3.0",
    "hydra-core>=1.3.2",
    "hydra-joblib-launcher>=1.2.0",
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.8",
    "opencv-python>=4.13.0.92",
    "opentsne>=1.0.4",
    "pandas>=3.0.1",
    "pillow>=12.1.1",
    "scikit-image>=0.26.0",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
    "tqdm>=4.67.3",
    "wandb>=0.25.1",
]

[project.optional-dependencies]
hub = ["huggingface_hub>=0.36", "safetensors>=0.4"]


[tool.ruff.lint.per-file-ignores]
"*.ipynb" = ["E402"]
