# @package _global_
dataset:
  dir: ./datasets
  name: fives
  name_eval: fives
  feature: disease
  image_size: [256, 256]
  sample_size: null
  kfold: 0

model:
  dropout: 0

train:
  label_smoothing: 0.1

stop:
  min_delta: 0.001
  patience: 15
  monitor: auroc

optim:
  lr_backbone: 1e-5
  lr_head: 1e-3
  wd: 1e-3
