# @package _global_
dataset:
  dir: ./datasets
  name: papila
  name_eval: papila
  feature: glaucoma
  image_size: [256, 256]
  sample_size: null
  kfold: 0

model:
  dropout: 0.5

train:
  label_smoothing: 0

stop:
  min_delta: 0.001
  patience: 15
  monitor: auroc

optim:
  lr_backbone: 1e-5
  lr_head: 5e-4
  wd: 1e-4
