defaults:
  - _self_
  - dataset: aptos

experiment_prefix: tsimcneb
sweep_name: clfproj_${experiment_prefix}_${dataset.name}_${dataset.feature}_${dataset.image_size[0]}

seed: null
device: cuda:0

model: 
  name: clf_${experiment_prefix}_${dataset.name}_${dataset.feature}_256/dataset.kfold=${dataset.kfold}_dataset=${dataset.name}.pt # checkpoint from finetuning (path to checkpoint inside checkpoints folder)

train:
  batch_size: 256
  epochs: 100
  num_workers: 4

# To disable wandb mode: disabled
wandb:
  mode: offline

hydra:
  searchpath:
          - file://configs
  run:
    dir: experiments

  sweep:
    dir: experiments/${sweep_name}
    subdir: ${hydra.job.override_dirname}

  sweeper:
    params:
      dataset.kfold: 1,2,3,4,5

  # To make names shorter instead of optimizer.lr, just lr
  job:
    config:
      override_dirname:
        kv_sep: "="
        item_sep: "_"
        exclude_keys:
          - model.name
          - dataset.name
          - dataset.name_eval
          - dataset.feature
          - experiment_prefix